### PR TITLE
Replaced the RelativeLayout with a ConstraintLayout (#5) and modified the UI (#4)

### PR DESCRIPTION
**Pull request by d-brott**
I replaced the RelativeLayout with a ConstraintLayout (#5) and modified the UI (#4). 

This is my first PR. Let me know if you have any feedback!

### CODE REVIEW

**Comment by roshniRam** [comment]
Sorry, I haven't been able to review the pr's, been busy with some stuff. Hope you understand, it will take till tomorrow.

**Comment by roshniRam** [comment]
You will have to work on this again, as there was no spinner before.

**Comment by d-brott** [comment]
I made some changes to activity_main.xml and strings.xml. I hope, everything works now.

**Comment by roshniRam** [comment]
Next time please reference the issue you are sending pr for,

**Comment by d-brott** [comment]
Sorry for the delay. Here is a screenshot of the UI.

whatsapp-direct-message screenshot

**Comment by aryadas98** [comment]
@d-brott please fill the NWoC registration form. You are on the leaderboard but you have not registered. Registration is mandatory to receive certificates and goodies.

**Pull request merged**
